// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	pullrequest "github.com/oak3/github-notifier/domain/pullrequest"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// FindNewPullRequests provides a mock function with given fields: prs
func (_m *Service) FindNewPullRequests(prs []*pullrequest.PullRequest) []*pullrequest.PullRequest {
	ret := _m.Called(prs)

	if len(ret) == 0 {
		panic("no return value specified for FindNewPullRequests")
	}

	var r0 []*pullrequest.PullRequest
	if rf, ok := ret.Get(0).(func([]*pullrequest.PullRequest) []*pullrequest.PullRequest); ok {
		r0 = rf(prs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*pullrequest.PullRequest)
		}
	}

	return r0
}

// HasBeenSeen provides a mock function with given fields: id
func (_m *Service) HasBeenSeen(id pullrequest.PRIdentifier) bool {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for HasBeenSeen")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(pullrequest.PRIdentifier) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// IsEmpty provides a mock function with no fields
func (_m *Service) IsEmpty() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsEmpty")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MarkPullRequestAsUnseen provides a mock function with given fields: pr
func (_m *Service) MarkPullRequestAsUnseen(pr *pullrequest.PullRequest) error {
	ret := _m.Called(pr)

	if len(ret) == 0 {
		panic("no return value specified for MarkPullRequestAsUnseen")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*pullrequest.PullRequest) error); ok {
		r0 = rf(pr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MarkPullRequestsAsSeen provides a mock function with given fields: prs
func (_m *Service) MarkPullRequestsAsSeen(prs []*pullrequest.PullRequest) {
	_m.Called(prs)
}

// TrackPullRequest provides a mock function with given fields: pr
func (_m *Service) TrackPullRequest(pr *pullrequest.PullRequest) bool {
	ret := _m.Called(pr)

	if len(ret) == 0 {
		panic("no return value specified for TrackPullRequest")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*pullrequest.PullRequest) bool); ok {
		r0 = rf(pr)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
