// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	port "github.com/oak/github-notifier/application/port"
)

// NotificationPort is an autogenerated mock type for the NotificationPort type
type NotificationPort struct {
	mock.Mock
}

// NotifyMessage provides a mock function with given fields: title, message
func (_m *NotificationPort) NotifyMessage(title string, message string) error {
	ret := _m.Called(title, message)

	if len(ret) == 0 {
		panic("no return value specified for NotifyMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(title, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotifyPullRequests provides a mock function with given fields: notifications
func (_m *NotificationPort) NotifyPullRequests(notifications []*port.PRNotificationData) error {
	ret := _m.Called(notifications)

	if len(ret) == 0 {
		panic("no return value specified for NotifyPullRequests")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]*port.PRNotificationData) error); ok {
		r0 = rf(notifications)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SupportsClickActions provides a mock function with no fields
func (_m *NotificationPort) SupportsClickActions() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportsClickActions")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewNotificationPort creates a new instance of NotificationPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationPort {
	mock := &NotificationPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
