// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	pullrequest "github.com/oak3/github-notifier/domain/pullrequest"
)

// NotificationPort is an autogenerated mock type for the NotificationPort type
type NotificationPort struct {
	mock.Mock
}

// NotifyNewPullRequests provides a mock function with given fields: title, prs
func (_m *NotificationPort) NotifyNewPullRequests(title string, prs []*pullrequest.PullRequest) error {
	ret := _m.Called(title, prs)

	if len(ret) == 0 {
		panic("no return value specified for NotifyNewPullRequests")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []*pullrequest.PullRequest) error); ok {
		r0 = rf(title, prs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SupportsClickActions provides a mock function with no fields
func (_m *NotificationPort) SupportsClickActions() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportsClickActions")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewNotificationPort creates a new instance of NotificationPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationPort {
	mock := &NotificationPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
