// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	pullrequest "github.com/oak3/github-notifier/domain/pullrequest"
)

// PRTrackingRepository is an autogenerated mock type for the PRTrackingRepository type
type PRTrackingRepository struct {
	mock.Mock
}

// HasNoSeenPRs provides a mock function with no fields
func (_m *PRTrackingRepository) HasNoSeenPRs() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HasNoSeenPRs")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// HasBeenSeen provides a mock function with given fields: id
func (_m *PRTrackingRepository) HasBeenSeen(id pullrequest.PRIdentifier) bool {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for HasBeenSeen")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(pullrequest.PRIdentifier) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ClearAllSeenPRs provides a mock function with no fields
func (_m *PRTrackingRepository) ClearAllSeenPRs() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ClearAllSeenPRs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Clear provides a mock function with no fields
func (_m *PRTrackingRepository) Clear() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Clear")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LoadAll provides a mock function with no fields
func (_m *PRTrackingRepository) LoadAll() ([]pullrequest.PullRequest, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LoadAll")
	}

	var r0 []pullrequest.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]pullrequest.PullRequest, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []pullrequest.PullRequest); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pullrequest.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: snapshots
func (_m *PRTrackingRepository) Save(snapshots []pullrequest.PullRequest) error {
	ret := _m.Called(snapshots)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]pullrequest.PullRequest) error); ok {
		r0 = rf(snapshots)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MarkAsSeen provides a mock function with given fields: id
func (_m *PRTrackingRepository) MarkAsSeen(id pullrequest.PRIdentifier) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for MarkAsSeen")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(pullrequest.PRIdentifier) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UnmarkAsSeen provides a mock function with given fields: id
func (_m *PRTrackingRepository) UnmarkAsSeen(id pullrequest.PRIdentifier) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for UnmarkAsSeen")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(pullrequest.PRIdentifier) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPRTrackingRepository creates a new instance of PRTrackingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPRTrackingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PRTrackingRepository {
	mock := &PRTrackingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
