// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	pullrequest "github.com/oak/github-notifier/domain/pullrequest"
)

// PRTrackingRepository is an autogenerated mock type for the PRTrackingRepository type
type PRTrackingRepository struct {
	mock.Mock
}

// Clear provides a mock function with no fields
func (_m *PRTrackingRepository) Clear() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Clear")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: prIdentifier
func (_m *PRTrackingRepository) Fetch(prIdentifier pullrequest.PRIdentifier) (*pullrequest.PullRequest, error) {
	ret := _m.Called(prIdentifier)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 *pullrequest.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(pullrequest.PRIdentifier) (*pullrequest.PullRequest, error)); ok {
		return rf(prIdentifier)
	}
	if rf, ok := ret.Get(0).(func(pullrequest.PRIdentifier) *pullrequest.PullRequest); ok {
		r0 = rf(prIdentifier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pullrequest.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(pullrequest.PRIdentifier) error); ok {
		r1 = rf(prIdentifier)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsEmpty provides a mock function with no fields
func (_m *PRTrackingRepository) IsEmpty() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsEmpty")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// LoadAll provides a mock function with no fields
func (_m *PRTrackingRepository) LoadAll() ([]*pullrequest.PullRequest, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LoadAll")
	}

	var r0 []*pullrequest.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*pullrequest.PullRequest, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*pullrequest.PullRequest); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*pullrequest.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: pullRequests
func (_m *PRTrackingRepository) Save(pullRequests []*pullrequest.PullRequest) error {
	ret := _m.Called(pullRequests)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]*pullrequest.PullRequest) error); ok {
		r0 = rf(pullRequests)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: pullRequest
func (_m *PRTrackingRepository) Update(pullRequest *pullrequest.PullRequest) error {
	ret := _m.Called(pullRequest)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*pullrequest.PullRequest) error); ok {
		r0 = rf(pullRequest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPRTrackingRepository creates a new instance of PRTrackingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPRTrackingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PRTrackingRepository {
	mock := &PRTrackingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
