// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"

	pullrequest "github.com/oak/github-notifier/domain/pullrequest"
)

// PullRequestRepository is an autogenerated mock type for the PullRequestRepository type
type PullRequestRepository struct {
	mock.Mock
}

// AuthenticatedUser provides a mock function with no fields
func (_m *PullRequestRepository) AuthenticatedUser() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AuthenticatedUser")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// FetchActivities provides a mock function with given fields: prs, since
func (_m *PullRequestRepository) FetchActivities(prs []*pullrequest.PullRequest, since time.Time) (map[string]pullrequest.PRActivityData, error) {
	ret := _m.Called(prs, since)

	if len(ret) == 0 {
		panic("no return value specified for FetchActivities")
	}

	var r0 map[string]pullrequest.PRActivityData
	var r1 error
	if rf, ok := ret.Get(0).(func([]*pullrequest.PullRequest, time.Time) (map[string]pullrequest.PRActivityData, error)); ok {
		return rf(prs, since)
	}
	if rf, ok := ret.Get(0).(func([]*pullrequest.PullRequest, time.Time) map[string]pullrequest.PRActivityData); ok {
		r0 = rf(prs, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]pullrequest.PRActivityData)
		}
	}

	if rf, ok := ret.Get(1).(func([]*pullrequest.PullRequest, time.Time) error); ok {
		r1 = rf(prs, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchPRStatus provides a mock function with given fields: owner, repo, number
func (_m *PullRequestRepository) FetchPRStatus(owner string, repo string, number int) (pullrequest.PRStatus, error) {
	ret := _m.Called(owner, repo, number)

	if len(ret) == 0 {
		panic("no return value specified for FetchPRStatus")
	}

	var r0 pullrequest.PRStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, int) (pullrequest.PRStatus, error)); ok {
		return rf(owner, repo, number)
	}
	if rf, ok := ret.Get(0).(func(string, string, int) pullrequest.PRStatus); ok {
		r0 = rf(owner, repo, number)
	} else {
		r0 = ret.Get(0).(pullrequest.PRStatus)
	}

	if rf, ok := ret.Get(1).(func(string, string, int) error); ok {
		r1 = rf(owner, repo, number)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchRequestedReviews provides a mock function with no fields
func (_m *PullRequestRepository) FetchRequestedReviews() ([]*pullrequest.PullRequest, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FetchRequestedReviews")
	}

	var r0 []*pullrequest.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*pullrequest.PullRequest, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*pullrequest.PullRequest); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*pullrequest.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchUserCreated provides a mock function with no fields
func (_m *PullRequestRepository) FetchUserCreated() ([]*pullrequest.PullRequest, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FetchUserCreated")
	}

	var r0 []*pullrequest.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*pullrequest.PullRequest, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*pullrequest.PullRequest); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*pullrequest.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPullRequestRepository creates a new instance of PullRequestRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPullRequestRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PullRequestRepository {
	mock := &PullRequestRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
