// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	time "time"

	pullrequest "github.com/oak3/github-notifier/domain/pullrequest"
	mock "github.com/stretchr/testify/mock"
)

// PullRequestRepository is an autogenerated mock type for the PullRequestRepository type
type PullRequestRepository struct {
	mock.Mock
}

// EnrichWithActivities provides a mock function with given fields: prs, since
func (_m *PullRequestRepository) EnrichWithActivities(prs []*pullrequest.PullRequest, since time.Time) error {
	ret := _m.Called(prs, since)

	if len(ret) == 0 {
		panic("no return value specified for EnrichWithActivities")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]*pullrequest.PullRequest, time.Time) error); ok {
		r0 = rf(prs, since)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FetchRequestedReviews provides a mock function with no fields
func (_m *PullRequestRepository) FetchRequestedReviews() ([]*pullrequest.PullRequest, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FetchRequestedReviews")
	}

	var r0 []*pullrequest.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*pullrequest.PullRequest, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*pullrequest.PullRequest); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*pullrequest.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchUserCreated provides a mock function with no fields
func (_m *PullRequestRepository) FetchUserCreated() ([]*pullrequest.PullRequest, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FetchUserCreated")
	}

	var r0 []*pullrequest.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*pullrequest.PullRequest, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*pullrequest.PullRequest); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*pullrequest.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPullRequestRepository creates a new instance of PullRequestRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPullRequestRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PullRequestRepository {
	mock := &PullRequestRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
