// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	pullrequest "github.com/oak3/github-notifier/domain/pullrequest"
)

// SeenRepository is an autogenerated mock type for the SeenRepository type
type SeenRepository struct {
	mock.Mock
}

// Clear provides a mock function with no fields
func (_m *SeenRepository) Clear() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Clear")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HasBeenSeen provides a mock function with given fields: id
func (_m *SeenRepository) HasBeenSeen(id pullrequest.PRIdentifier) bool {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for HasBeenSeen")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(pullrequest.PRIdentifier) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// HasNoSeenPRs provides a mock function with no fields
func (_m *SeenRepository) HasNoSeenPRs() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HasNoSeenPRs")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MarkAsSeen provides a mock function with given fields: id
func (_m *SeenRepository) MarkAsSeen(id pullrequest.PRIdentifier) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for MarkAsSeen")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(pullrequest.PRIdentifier) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UnmarkAsSeen provides a mock function with given fields: id
func (_m *SeenRepository) UnmarkAsSeen(id pullrequest.PRIdentifier) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for UnmarkAsSeen")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(pullrequest.PRIdentifier) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSeenRepository creates a new instance of SeenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSeenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SeenRepository {
	mock := &SeenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
