// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	pullrequest "github.com/oak3/github-notifier/domain/pullrequest"
	mock "github.com/stretchr/testify/mock"
)

// UIPort is an autogenerated mock type for the UIPort type
type UIPort struct {
	mock.Mock
}

// UpdateDisplay provides a mock function with given fields: requestedReviewPRs, userCreatedPRs, seenRepo
func (_m *UIPort) UpdateDisplay(requestedReviewPRs []*pullrequest.PullRequest, userCreatedPRs []*pullrequest.PullRequest, seenRepo pullrequest.SeenRepository) {
	_m.Called(requestedReviewPRs, userCreatedPRs, seenRepo)
}

// NewUIPort creates a new instance of UIPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUIPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *UIPort {
	mock := &UIPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
