// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	pullrequest "github.com/oak3/github-notifier/domain/pullrequest"
)

// UIPort is an autogenerated mock type for the UIPort type
type UIPort struct {
	mock.Mock
}

// UpdateDisplay provides a mock function with given fields: requestedReviewPRs, userCreatedPRs, trackingService
func (_m *UIPort) UpdateDisplay(requestedReviewPRs []*pullrequest.PullRequest, userCreatedPRs []*pullrequest.PullRequest, trackingService *pullrequest.TrackingService) {
	_m.Called(requestedReviewPRs, userCreatedPRs, trackingService)
}

// NewUIPort creates a new instance of UIPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUIPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *UIPort {
	mock := &UIPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
